### ISSUE TITLE
How To  Add Persistent Volumes To Docker Compose File

### ISSUE THREAD

**Issue by lewismunene020** [EvilFreelancer/docker-routeros#49]
Came Across  this docker container recently .
 Is  there  a way to  add  persistent  docker volumes to  avoid  loosing data  when the container gores down.

There should be a  way to map a certian folder and  make  it persistent in every  build .

Kindly help  if possible

**Comment by EvilFreelancer** [comment]
You absolutely can!

First you need to create a `Persistent Volume` with help `docker volume`, then mount this volume to a Docker-container.

When you start your Docker-container, you will need to connect into a shell of container and copy a VDI image from root of container to `Persistent Volume` folder.

On the next step you need to adjust your `entrypoint.sh` script to use the path inside the container that's mapped to `Persistent Volume`.

There is a caveat with this approach regarding ROS updates. Since your ROS environment is running within a QEMU instance, updating the Docker image itself won't directly update the ROS installation inside the VM.

You'll need to manually manage ROS upgrades within the QEMU environment separately.

**Comment by lewismunene020** [comment]
How about  doing so  in  a Docker compose  file

**Comment by EvilFreelancer** [comment]
Something like this:

```yml
volumes:
- ./image:/image
```

Then:

```
docker-compose up -d
docker-compose exec ros bash
```

Then find your VDI and copy to PV, and so on.

**Comment by lewismunene020** [comment]
Thanks  for that @EvilFreelancer .

**Comment by EvilFreelancer** [comment]
Glad to help!
